language: objective-c

before_install:
  - gem install activesupport
  - gem install cocoapods -v 0.37.2
  - gem install slather -v 1.8

script: ./build.sh ci

# Whitelist for branches
branches:
  only:
    - master

after_success:
  - slather
